
inherits = "pop-dark"
"ui.background" ={}
"ui.virtual.jump-label"="red"

"ui.bufferline"              = { fg = "text", bg = "widget" }
"ui.bufferline.active"       = { fg = "white", bg = "brownN" }
"ui.bufferline.background"   = { bg = "background" }
'ui.gutter' = { bg = 'background' }
